export interface Spell {
	uuid: string,
	level: number,
	name: string,
	type: string,
	castingTime: string,
	range: string,
	components: string,
	duration: string,
	description: string,
	higherLevelDescrption?: string,
	castedBy: string,
	picture?: string,
	selected?: boolean,
}